### ISSUE TITLE
NoSuchMethodError android.media.ImageReader.nativeInit for Paparazzi 1.2.0

### ISSUE THREAD

**Issue by jannisveerkamp** [cashapp/paparazzi#688]
**Description**
After updating Paparazzi from `1.1.0` to `1.2.0` my tests fail with the following error:

```
JNIHelp F 01-19 08:29:28  3178 7027946 java.lang.NoSuchMethodError: Method android.media.ImageReader.nativeInit(Ljava/lang/Object;IIIIJ)V not found
JNIHelp F 01-19 08:29:28  3178 7027946 RegisterNatives failed for 'android/media/ImageReader'; aborting...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000012865689e, pid=3178, tid=4355
#
# JRE version: OpenJDK Runtime Environment Homebrew (11.0.16.1) (build 11.0.16.1+0)
# Java VM: OpenJDK 64-Bit Server VM Homebrew (11.0.16.1+0, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [libandroid_runtime.dylib+0x1589e]  JNI_OnLoad+0x54e
#
```

I also see the following Stacktrace in the logs:
<details>
<summary>Stacktracke</summary>

```
Current thread (0x00007fdf58809800):  JavaThread "Test worker" [_thread_in_native, id=4867, stack(0x0000700009bcc000,0x0000700009ccc000)]

Stack: [0x0000700009bcc000,0x0000700009ccc000],  sp=0x0000700009cc8fe0,  free space=1011k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libandroid_runtime.dylib+0x1589e]  JNI_OnLoad+0x54e
C  [libjava.dylib+0x71a7]  Java_java_lang_ClassLoader_00024NativeLibrary_load0+0xd1
j  java.lang.ClassLoader$NativeLibrary.load0(Ljava/lang/String;ZZ)Z+0 java.base@11.0.16.1
j  java.lang.ClassLoader$NativeLibrary.load()Z+56 java.base@11.0.16.1
j  java.lang.ClassLoader$NativeLibrary.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)Z+216 java.base@11.0.16.1
j  java.lang.ClassLoader.loadLibrary0(Ljava/lang/Class;Ljava/io/File;)Z+46 java.base@11.0.16.1
j  java.lang.ClassLoader.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)V+70 java.base@11.0.16.1
j  java.lang.Runtime.load0(Ljava/lang/Class;Ljava/lang/String;)V+57 java.base@11.0.16.1
j  java.lang.System.load(Ljava/lang/String;)V+7 java.base@11.0.16.1
j  com.android.layoutlib.bridge.Bridge.loadNativeLibraries(Ljava/lang/String;)V+105
j  com.android.layoutlib.bridge.Bridge.loadNativeLibrariesIfNeeded(Lcom/android/ide/common/rendering/api/ILayoutLog;Ljava/lang/String;)Z+7
j  com.android.layoutlib.bridge.Bridge.init(Ljava/util/Map;Ljava/io/File;Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;Lcom/android/ide/common/rendering/api/ILayoutLog;)Z+22
j  app.cash.paparazzi.internal.Renderer.prepare()Lapp/cash/paparazzi/internal/SessionParamsBuilder;+382
j  app.cash.paparazzi.Paparazzi.prepare(Lorg/junit/runner/Description;)V+96
j  app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate()V+8
j  app.cash.paparazzi.agent.AgentTestRule$apply$1.evaluate()V+14
j  org.junit.runners.ParentRunner$3.evaluate()V+4
j  org.junit.runners.BlockJUnit4ClassRunner$1.evaluate()V+11
j  org.junit.runners.ParentRunner.runLeaf(Lorg/junit/runners/model/Statement;Lorg/junit/runner/Description;Lorg/junit/runner/notification/RunNotifier;)V+17
j  org.junit.runners.BlockJUnit4ClassRunner.runChild(Lorg/junit/runners/model/FrameworkMethod;Lorg/junit/runner/notification/RunNotifier;)V+38
j  org.junit.runners.BlockJUnit4ClassRunner.runChild(Ljava/lang/Object;Lorg/junit/runner/notification/RunNotifier;)V+6
j  org.junit.runners.ParentRunner$4.run()V+12
j  org.junit.runners.ParentRunner$1.schedule(Ljava/lang/Runnable;)V+1
j  org.junit.runners.ParentRunner.runChildren(Lorg/junit/runner/notification/RunNotifier;)V+44
j  org.junit.runners.ParentRunner.access$100(Lorg/junit/runners/ParentRunner;Lorg/junit/runner/notification/RunNotifier;)V+2
j  org.junit.runners.ParentRunner$2.evaluate()V+8
j  org.junit.runners.ParentRunner.run(Lorg/junit/runner/notification/RunNotifier;)V+24
j  org.junit.runners.Suite.runChild(Lorg/junit/runner/Runner;Lorg/junit/runner/notification/RunNotifier;)V+2
j  org.junit.runners.Suite.runChild(Ljava/lang/Object;Lorg/junit/runner/notification/RunNotifier;)V+6
j  org.junit.runners.ParentRunner$4.run()V+12
j  org.junit.runners.ParentRunner$1.schedule(Ljava/lang/Runnable;)V+1
j  org.junit.runners.ParentRunner.runChildren(Lorg/junit/runner/notification/RunNotifier;)V+44
j  org.junit.runners.ParentRunner.access$100(Lorg/junit/runners/ParentRunner;Lorg/junit/runner/notification/RunNotifier;)V+2
j  org.junit.runners.ParentRunner$2.evaluate()V+8
j  org.junit.runners.ParentRunner$3.evaluate()V+4
j  org.junit.runners.ParentRunner.run(Lorg/junit/runner/notification/RunNotifier;)V+24
j  org.junit.runner.JUnitCore.run(Lorg/junit/runner/Runner;)Lorg/junit/runner/Result;+37
j  org.junit.runner.JUnitCore.run(Lorg/junit/runner/Request;)Lorg/junit/runner/Result;+5
j  org.junit.vintage.engine.execution.RunnerExecutor.execute(Lorg/junit/vintage/engine/descriptor/RunnerTestDescriptor;)V+42
j  org.junit.vintage.engine.VintageTestEngine.executeAllChildren(Lorg/junit/vintage/engine/descriptor/VintageEngineDescriptor;Lorg/junit/platform/engine/EngineExecutionListener;)V+41
j  org.junit.vintage.engine.VintageTestEngine.execute(Lorg/junit/platform/engine/ExecutionRequest;)V+23
j  org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(Lorg/junit/platform/engine/TestDescriptor;Lorg/junit/platform/engine/EngineExecutionListener;Lorg/junit/platform/engine/ConfigurationParameters;Lorg/junit/platform/engine/TestEngine;)V+24
j  org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(Lorg/junit/platform/launcher/core/LauncherDiscoveryResult;Lorg/junit/platform/engine/EngineExecutionListener;)V+100
j  org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(Lorg/junit/platform/launcher/core/InternalTestPlan;Lorg/junit/platform/engine/EngineExecutionListener;Lorg/junit/platform/launcher/TestExecutionListener;)V+63
j  org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(Lorg/junit/platform/launcher/core/InternalTestPlan;Lorg/junit/platform/launcher/TestExecutionListener;)V+6
j  org.junit.platform.launcher.core.EngineExecutionOrchestrator$$Lambda$196.accept(Ljava/lang/Object;)V+12
j  org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(Lorg/junit/platform/engine/ConfigurationParameters;Lorg/junit/platform/launcher/core/ListenerRegistry;Ljava/util/function/Consumer;)V+51
j  org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(Lorg/junit/platform/launcher/core/InternalTestPlan;[Lorg/junit/platform/launcher/TestExecutionListener;)V+23
j  org.junit.platform.launcher.core.DefaultLauncher.execute(Lorg/junit/platform/launcher/core/InternalTestPlan;[Lorg/junit/platform/launcher/TestExecutionListener;)V+6
j  org.junit.platform.launcher.core.DefaultLauncher.execute(Lorg/junit/platform/launcher/LauncherDiscoveryRequest;[Lorg/junit/platform/launcher/TestExecutionListener;)V+34
j  org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(Lorg/junit/platform/launcher/LauncherDiscoveryRequest;[Lorg/junit/platform/launcher/TestExecutionListener;)V+6
j  org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(Lorg/junit/platform/launcher/LauncherDiscoveryRequest;[Lorg/junit/platform/launcher/TestExecutionListener;)V+13
j  org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses()V+58
j  org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(Lorg/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor;)V+1
j  org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop()V+4
j  org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop()V+4
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x3be5b1]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x257
V  [libjvm.dylib+0x676de7]  invoke(InstanceKlass*, methodHandle const&, Handle, bool, objArrayHandle, BasicType, objArrayHandle, bool, Thread*)+0x813
V  [libjvm.dylib+0x67658a]  Reflection::invoke_method(oopDesc*, Handle, objArrayHandle, Thread*)+0xf4
V  [libjvm.dylib+0x440bdb]  JVM_InvokeMethod+0x1cb
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0 java.base@11.0.16.1
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+100 java.base@11.0.16.1
j  jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+6 java.base@11.0.16.1
j  java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+59 java.base@11.0.16.1
j  org.gradle.internal.dispatch.ReflectionDispatch.dispatch(Lorg/gradle/internal/dispatch/MethodInvocation;)V+19
j  org.gradle.internal.dispatch.ReflectionDispatch.dispatch(Ljava/lang/Object;)V+5
j  org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(Ljava/lang/Object;)V+22
j  org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;+177
j  com.sun.proxy.$Proxy2.stop()V+9
j  org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run()V+7
j  org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(Ljava/lang/Runnable;)V+1
j  org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(Lorg/gradle/process/internal/worker/WorkerProcessContext;)V+80
j  org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(Ljava/lang/Object;)V+5
j  org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(Lorg/gradle/process/internal/worker/WorkerProcessContext;)V+65
j  org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call()Ljava/lang/Void;+293
j  org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call()Ljava/lang/Object;+1
j  worker.org.gradle.process.internal.worker.GradleWorkerMain.run()V+250
j  worker.org.gradle.process.internal.worker.GradleWorkerMain.main([Ljava/lang/String;)V+7
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x3be5b1]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x257
V  [libjvm.dylib+0x403608]  jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*)+0x10a
V  [libjvm.dylib+0x4063be]  jni_CallStaticVoidMethod+0x164
C  [libjli.dylib+0x9e80]  JavaMain+0xa9d
C  [libjli.dylib+0xc073]  ThreadJavaMain+0x9
C  [libsystem_pthread.dylib+0x6259]  _pthread_start+0x7d
C  [libsystem_pthread.dylib+0x1c7b]  thread_start+0xf
```

</details>

I tried to downgrade manually to layoutlib 32 but the same error occurred.

**Steps to Reproduce**
Simply run `./gradlew recordPaparazziDebug` or start any test from AS.

**Additional information:**
- Paparazzi Version: 1.2.0
- OS: macOS 13.1
- Compile SDK: 33
- Gradle Version: 7.6
- Android Gradle Plugin Version: 7.4.0 (+Electric Eel)
- Compose 1.2.1
- Kotlin 1.7.10

**Comment by apkelly** [comment]
Same for me after updating from Paparazzi 1.1.0 to 1.2.0
```
JNIHelp F 01-20 00:35:10 69894 2452643 java.lang.NoSuchMethodError: Method android.media.ImageReader.nativeInit(Ljava/lang/Object;IIIIJ)V not found
#
JNIHelp F 01-20 00:35:10 69894 2452643 RegisterNatives failed for 'android/media/ImageReader'; aborting...
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001251e489e, pid=69894, tid=6403
#
# JRE version: OpenJDK Runtime Environment Zulu11.45+27-CA (11.0.10+9) (build 11.0.10+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu11.45+27-CA (11.0.10+9-LTS, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [libandroid_runtime.dylib+0x1589e]  JNI_OnLoad+0x54e
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/andy/Development/assembly-payments/vaa-android/x-userguide/hs_err_pid69894.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
Paparazzi Version: 1.2.0
Compose: 1.3.1
Compose Compiler: 1.3.2
Kotlin: 1.7.20
AGP: 7.2.2

**Comment by jrodbx** [comment]
Interesting...can somebody provide a MRE?  Also, do you happen to use ImageReader classes in your respective apps?

**Comment by jannisveerkamp** [comment]
I feel kind of stupid now, but we still had references of the paparazzi lib outside the plugin. We didn't update both versions...
So everything works 🙈

**Comment by jrodbx** [comment]
oh nice, thanks for sharing.  @apkelly similar issue?

**Comment by apkelly** [comment]
Let me check and get back to you.
